language: ruby
rvm:
 - 2.4.2
 - 2.4.3

before_install:
# - bundle install --gemfile=.travis.gemfile
# - bundle lock --lockfile=.travis.gemfile.lock --add-platform ruby
# - bundle lock --lockfile=.travis.gemfile.lock --add-platform x86_64-linux

install:
  # Bundler downgrade should be removed when the issue is fixed upstream
  #gem uninstall bundler -x
  #gem install bundler -v ">1.1.4"

bundler_args: --without production

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

gemfile:
 #- Gemfile
 - gemfiles/travis.gemfile

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
